wandb_version: 1

model:
  desc: null
  value: A
sign:
  desc: null
  value: 0
weight norm:
  desc: null
  value: false
tau:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684190564.514011
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.15.2
      8:
      - 5
